data_source vertica_local:
  type: vertica
  connection:
    host: ${vertica_host}
    port: '5433'
    username: ${vertica_user}
    password: ${vertica_password}
    database: ${vertica_db}
    schema: ${vertica_schema}